stages:
 - build

build:
 stage: build
 image:
  name: python:3.7-alpine3.9
  entrypoint: [""]
 script:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install django
  - python manage.py makemigrations
  - python manage.py runserver
  - curl --data "username=admin&first_name=Administrator&last_name=LastName&is_tenant=true&password=mostsecure&confirm_password=mostsecure&email=admin@localhost.com&is_superuser=true"
  - curl localhost:8000/api/v1/users/
